### ISSUE TITLE
write_shapefile

### ISSUE THREAD

**Issue by chuwenhao123** [pyswmm/swmmio#202]
In Swmmio version 0.6.7, there is an issue with the created polygon shapefile not loading correctly in ArcGIS. The extents of the polygons are being ignored. I discovered the problem while referring to this link (https://swmmio.readthedocs.io/en/v0.6.7/_modules/swmmio/utils/spatial.html#write_shapefile), where it seems that you forgot to add the geometry for polygon.
 `        if geomtype== 'polygon':
            w.poly([row.coords]).` 
As shown in the provided image, a fixed version is needed. 
![image](https://github.com/pyswmm/swmmio/assets/51478550/526f1059-323e-4f9a-8c0c-bff4f28f0c77)

**Comment by chuwenhao123** [comment]
What's wrong with this guy?  Already two months with no replies?

**Comment by bemcdonnell** [comment]
@chuwenhao123 this is an open source software project run by awesome passionate volunteers.  You can be a volunteer and help the team if you’d like - the bug fix would be done much faster with you help.  Can you help the project? :-)

**Comment by chuwenhao123** [comment]
@bemcdonnell Hi, I have already created a pull request. Hope it can be helpful.

**Comment by chuwenhao123** [comment]
Hello @bemcdonnell, I noticed an error while merging the files. The specific error message is as follows: "AttributeError: 'ImageDraw' object has no attribute 'textsize'." It appears that this issue is related to Pillow version 10.0, as the ImageDraw.textsize function has been deprecated.

You may want to consider downgrading the version of Pillow to resolve this problem. You can do this by specifying the desired version in your project's dependencies.

Here is the error message for reference:
![image](https://github.com/pyswmm/swmmio/assets/51478550/db3751a8-cd66-42bc-9652-deb967ac457d)


Additionally, there is an open issue on the Pillow GitHub repository related to this problem, which you can track [here](https://github.com/python-pillow/Pillow/issues/7277). I hope this helps you address the issue.

**Comment by bemcdonnell** [comment]
@aerispaha @karosc how would you like this handled ?

**Comment by aerispaha** [comment]
Hey @chuwenhao123 and others, can we close this issue since we've merged #205?
