### ISSUE TITLE
Negative offset elevations handled incorrectly in profile plot

### ISSUE THREAD

**Issue by Nils-TalTech** [pyswmm/swmmio#204]
Hi,
If pipe offsets are set in swmm to "Elevation" i.e. absolute numbers and these are negative - which means the pipeline is below the sealevel the function def build_profile_plot(ax, model, path_selection) handles these negative numbers as depths and subtracts the height from the manhole invert resulting incorrect profile.
Attached:
demo3.pdf swmm with negative offset elevations
faulty_profile - incorrect profile created by build_profile_plot(ax, model, path_selection) 

[demo3.pdf](https://github.com/pyswmm/swmmio/files/12523897/demo3.pdf)
![faulty_profile](https://github.com/pyswmm/swmmio/assets/65945295/b01c87ad-8a79-438b-a0fd-0ba8be0d27b0)

Python 3.10
swmmio 0.6.7
Regards,
Nils

**Comment by bemcdonnell** [comment]
@Nils-TalTech, good catch. Would you be interested in contributing a fix to the code to handle the negative inverts? I can but it will be quite a while. If you could put this test into a zip file so we can recreate it, that will help greatly

**Comment by Nils-TalTech** [comment]
Hi @bemcdonnell,
Ok, I'll give it a try. Although I'm not a professional programmer (but just a professional water engineer ;))
Please find the test zip enclosed
Regards,
Nils
[demo_profile_bug_negative_elevations.zip](https://github.com/pyswmm/swmmio/files/12544893/demo_profile_bug_negative_elevations.zip)

**Comment by bemcdonnell** [comment]
@Nils-TalTech none of us are professionals - just making it up as we go and hiding behind the name “Hydroinformatics engineers.” 🤣 Follow the code inward to swmmio and you should see what’s going on with the profile plotter.  I have a feeling that this issue is going to be fairly straightforward to resolve

**Comment by everettsp** [comment]
Submitted pull request with fix
