### ISSUE TITLE
Updates to support read/write of additional INP sections

### ISSUE THREAD

**Issue by kaklise** [pyswmm/swmmio#217]
I have been using swmmio to add stormwater/wastewater analysis to WNTR.  The ability to read, modify, and write INP files using pandas DataFrames has been very helpful!  I found a few issues when comparing simulation results with and without the read/write of INP files ([XSECTIONS], [INFLOWS], and [CURVES]). I also needed to support a few additional sections in Model.inp ([CONTROLS] and [PATTERNS]).  I stored controls and patterns in DataFrames with 1 line per entry.  I'm using INP files from SWMM and swmmio to test functionality.  Let me know if you're interested in a PR!

**Comment by aerispaha** [comment]
@kaklise, I'm so happy that swmmio has been helpful for you. 100% we're interested in a PR! Please feel free to submit a PR at your convenience, then we can continue the conversation there :)
