### ISSUE TITLE
'delim_whitespace' will be depreciated

### ISSUE THREAD

**Issue by bowguy** [pyswmm/swmmio#221]
Getting a warning:
_FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead_

Change needed in
 swmmio\utils\dataframes.py:107
 swmmio\utils\dataframes.py:167
 swmmio\utils\text.py:265

**Comment by bemcdonnell** [comment]
@bowguy, can you submit a pull request to fix this?

**Comment by bowguy** [comment]
Sure.  I think I did one of those once...

**Comment by bowguy** [comment]
Pull request creation failed. Validation failed: must be a collaborator ??

**Comment by bemcdonnell** [comment]
@bowguy Fork the project into your github account and push your changes there. Then submit a PR from your fork

**Comment by bowguy** [comment]
Done
