### ISSUE TITLE
Calling float on a single element Series is deprecated

### ISSUE THREAD

**Issue by dirwin5** [pyswmm/swmmio#223]
Getting multiple FutureWarnings in swmmio/graphics/profiler.py. `FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead`. I'll try to fix and submit a PR.

Affected lines:
swmmio/graphics/profiler.py:35
swmmio/graphics/profiler.py:47
swmmio/graphics/profiler.py:57
swmmio/graphics/profiler.py:90
swmmio/graphics/profiler.py:94
swmmio/graphics/profiler.py:139
swmmio/graphics/profiler.py:140
swmmio/graphics/profiler.py:147
swmmio/graphics/profiler.py:148
swmmio/graphics/profiler.py:149
swmmio/graphics/profiler.py:277
swmmio/graphics/profiler.py:281
swmmio/graphics/profiler.py:301
swmmio/graphics/profiler.py:305

**Comment by bemcdonnell** [comment]
@dirwin5, thanks for noticing this.  We’d love the PR if you have time.  Was this an change in a recent release of pandas?

**Comment by dirwin5** [comment]
Hi @bemcdonnell, yes it's pandas related, I believe since Pandas 2.0. There's an issue on the pandas-dev repo related to it here https://github.com/pandas-dev/pandas/issues/51101

I've drafted a PR, thanks.

**Comment by aerispaha** [comment]
Closed via #224
